export {
  COLORS,
  COLOR_COUNT,
  DEFAULT_RULES,
  directExplosionRadiusForSelection,
  FORECAST_PLAN_BONUS,
  FORECAST_PLAN_CHAIN_BONUS_PER_TARGET,
  FORECAST_PLAN_SELECTION_COUNT,
  GAME_VERSION,
  INPUT_SCHEMA_VERSION,
  RULE_VERSION,
  selectionDurationMultiplierPercent,
  selectionRadiusMultiplierPercent,
  WAVE_DEFINITIONS,
  WAVE_KINDS,
  WAVE_INTERVAL_TICKS,
  mergeRules,
  rulesFingerprint,
} from "../config/rules.js";
